# Generated by Django 3.2.4 on 2021-06-21 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_product_is_active'),
        ('mainapp', '0003_productcategory_is_active'),
    ]

    operations = [
    ]
