# Generated by Django 3.2.4 on 2021-06-21 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_merge_20210622_0152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={},
        ),
    ]
