name = input("Ваше имя?")
family = input("Ваша фамилия?")
age = int(input("Ваш возраст??"))
country = input("Из какой вы страны?")
print(f"Вас зовут {name} {family}, Вам {age} лет и вы из {country} ")
